import type { Scene } from '../../render-engine'

// §3 fhs-you — the section's line is that two of these branches are "windows into the running kernel,
// not files on any disk". That is a contrast, so the scene is two columns and nothing else: the same
// interface on the left and the right, but only one side survives a power cut.
export const realVsVirtual: Scene = {
  id: 'real-vs-virtual',
  cols: 2,
  padding: 0.16,
  nodes: [
    {
      id: 'real',
      label: 'Real files, on a real disk',
      sub: 'still there after a reboot',
      pattern: 'storage',
      children: [
        { id: 'r-home', label: '/home', sub: 'one directory per user — ~ is yours', pattern: 'storage', icon: 'users' },
        { id: 'r-root', label: '/root', sub: 'the admin user’s home, not /', pattern: 'storage', icon: 'key' },
        { id: 'r-tmp', label: '/tmp', sub: 'scratch space, wiped on reboot', pattern: 'external', icon: 'ban' },
      ],
    },
    {
      id: 'virtual',
      label: 'Generated by the kernel, live',
      sub: 'nothing here is stored anywhere',
      pattern: 'network',
      children: [
        { id: 'v-dev', label: '/dev', sub: 'every device as a file', pattern: 'network', icon: 'harddrive' },
        { id: 'v-proc', label: '/proc', sub: 'live process and CPU state', pattern: 'network', icon: 'gears' },
        { id: 'v-sys', label: '/sys', sub: 'kernel knobs you can read and set', pattern: 'network', icon: 'wrench' },
      ],
    },
  ],
  edges: [],
}
