import type { Section } from '../types'

export const fhsYou: Section = {
  id: 'fhs-you',
  title: 'Your files & the virtual trees',
  scene: 'real-vs-virtual',
  slide: `## Your files & the virtual trees

The rest of the tree is **yours to use** — plus two branches that are windows into the *running kernel*, not files on any disk.

### Where you live
- **\`/home\`** — one directory per user; yours is \`/home/<you>\`, and **\`~\`** is a shorthand for it
- **\`/root\`** — the **root** (admin) user's home; *not* the same as \`/\`
- **\`/tmp\`** — scratch space anyone can use; **wiped on reboot**, so never keep anything you need there

### The virtual filesystems
- **\`/dev\`** — every device as a file: \`/dev/sda\` (disk), \`/dev/null\` (the void), \`/dev/random\`
- **\`/proc\` · \`/sys\`** — **generated by the kernel on the fly**: \`/proc/cpuinfo\`, \`/proc/<pid>/…\` — read them and you're reading **live kernel state** (Course 4), not a disk

A tree of real files *and* live windows into the machine — all through the same file interface.`,
  narration:
    'Now the parts of the tree that are yours, and a couple that are stranger than they look. First, slash-home. This is where user files live, with one subdirectory per person on the system — if your username is sam, your home directory is slash-home-slash-sam, and it\'s the one place you can always freely create, edit, and delete files without special permission. It\'s so central that the shell gives it a shorthand: the tilde character, which always means your home directory. There\'s a related one, slash-root — that\'s the home directory of the administrative user, who is literally named root, and it\'s a common trap for beginners: slash-root, the admin\'s home, is a completely different thing from plain slash, the top of the whole tree. Then there\'s slash-tmp, temporary scratch space that any program or user can scribble in — but with a catch that has burned everyone at least once: slash-tmp is wiped clean on every reboot, so never, ever leave something there you actually need to keep. Now for the genuinely mind-bending ones. Slash-dev is where all those device files live — your disk as slash-dev-slash-sda, and special ones like slash-dev-slash-null, the black hole that swallows anything written to it, and slash-dev-slash-random, an endless source of random bytes. But the strangest of all are slash-proc and slash-sys. These directories are not stored on any disk at all. The kernel generates their contents on the fly, the instant you look, as a live window into itself. Read the file slash-proc-slash-cpuinfo and the kernel manufactures a description of your CPU right then. There\'s a directory under slash-proc for every single running process, named by its process ID, and reading inside it tells you exactly what that program is doing this moment — something we\'ll lean on heavily in the next course. So the filesystem is this remarkable hybrid: a tree of real files on disk, and also a set of live, always-current windows into the running machine — and the magic is that you touch both through the exact same file interface. Now that we know the map, let\'s learn to actually walk it.',
}
